---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'

options:
  package_manager_path: /usr/bin/microdnf

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  
  python_interpreter:
    package_system: python3.11
    python_path: /usr/bin/python3.11

  python:
    - six
    - psutil
    - ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt
    - kubernetes

images:
  base_image:
    # name: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:latest
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:latest

additional_build_files:
    - src: ansible.cfg
      dest: configs
    - src: openshift-clients-4.15.0-202403061609.p0.gd6175eb.assembly.stream.el9.x86_64.rpm
      dest: rpms

additional_build_steps:

  prepend_base:
    - COPY _build/rpms/*.rpm /tmp/openshift-clients.rpm
    - RUN $PKGMGR install -y bash-completion
    - RUN rpm -ivh /tmp/openshift-clients.rpm
    - RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc && rpm -Uvh https://packages.microsoft.com/config/rhel/8/packages-microsoft-prod.rpm && microdnf install -y azure-cli

  prepend_galaxy:
    - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg

  prepend_final: |
    RUN whoami
    RUN cat /etc/os-release

  append_final:
    - RUN echo This is a post-install command!
    - RUN ls -la /etc