---
- name: Create cluster
  hosts: localhost
  gather_facts: false
  collections:
  - servicenow.itsm


  vars:
    state: present

  roles:
    - role: kubernetes
      vars:
        cluster_state: "{{ state }}" 
    # - role: acm
    #   vars:
    #     cluster_state: "{{ state }}"
