---
- name: Create cluster
  hosts: localhost
  gather_facts: false

  # roles:
  #   - role: google.cloud.gcloud

  tasks:  

  # - name: Install bottle python package
  #   ansible.builtin.pip:
  #     name: pyyaml

  - name: create a cluster
    google.cloud.gcp_container_cluster:
      
      name: my-cluster
      
      initial_node_count: 1
      
      node_config:
        machine_type: n1-standard-4
        disk_size_gb: 500
      
      location: northamerica-northeast1-a
      
      project: openenv-z7ckj
      
      auth_kind: serviceaccount
      
      binary_authorization: 
        enabled: false

      kubectl_context: "gk"
      kubectl_path: "./gk.yaml"

      legacy_abac:
        enabled: true

      state: present

    register: gke_cluster_artifactcluster

  - name: Build credentials
    ansible.builtin.shell: |
      gcloud auth activate-service-account --key-file=${GCE_CREDENTIALS_FILE_PATH} && \
      gcloud container clusters get-credentials my-cluster --location=northamerica-northeast1-a --project=openenv-z7ckj && \
      kubectl create sa ggg && \
      kubectl create clusterrolebinding ggg-cluster-admin --clusterrole=cluster-admin --serviceaccount=default:ggg

  - name: Get token
    ansible.builtin.shell: kubectl create token ggg
    register: gke_token

  - name: debug
    ansible.builtin.debug:
      var: gke_token

  # - name: debug
  #   ansible.builtin.debug:
  #     msg: "{{ lookup('ansible.builtin.env', 'GCE_CREDENTIALS_FILE_PATH') }}"

  - name: debug_gk
    ansible.builtin.debug:
      msg: "{{ lookup('ansible.builtin.template', '~/.kube/config') }}"
