---
- name: Create cluster
  hosts: localhost
  gather_facts: false

  # roles:
  #   - role: google.cloud.gcloud

  tasks:  

  # - name: Install bottle python package
  #   ansible.builtin.pip:
  #     name: pyyaml

  - name: create a cluster
    google.cloud.gcp_container_cluster:
      
      name: my-cluster
      
      initial_node_count: 1
      
      node_config:
        machine_type: n1-standard-4
        disk_size_gb: 500
      
      location: northamerica-northeast1-a
      
      project: openenv-z7ckj
      
      auth_kind: serviceaccount
      
      binary_authorization: 
        enabled: false

      kubectl_context: "gk"
      kubectl_path: "./gk.yaml"

      legacy_abac:
        enabled: true

      state: present

    register: gke_cluster_artifactcluster

  - name: Retrieve kubeconfig
    ansible.builtin.shell: gcloud container clusters get-credentials my-cluster --location=northamerica-northeast1-a --project=openenv-z7ckj
    register: gke_kubeconfig
    when: cluster_state == “present”

  - name: debug
    ansible.builtin.debug:
      msg: "{{ lookup('ansible.builtin.template', './templates/import-cluster.yaml') }}"

  - name: debug_gk
    ansible.builtin.debug:
      msg: "{{ lookup('ansible.builtin.template', '~/.kube/config') }}"
