---
- name: Create cluster
  hosts: localhost
  gather_facts: false
  
  vars:
    state: absent

  roles:
    - role: kubernetes
      vars:
        cluster_state: "{{ state }}" 
    # - role: acm
    #   vars:
    #     cluster_state: "{{ state }}" 

