---
- name: Upgrade GKE cluster
  hosts: localhost
  gather_facts: false
  collections:
  - servicenow.itsm

  vars:
    cluster_state: present
    zone: northamerica-northeast1-a

  vars_prompt:    
    - name: cluster_name
      prompt: Cluster name
      private: false
    
    - name: version
      prompt: Cluster Version
      default: 1.27
      private: false


  tasks:

  - name: Upgrade the Cluster version
    ansible.builtin.shell: |
      gcloud auth activate-service-account --key-file=${GCE_CREDENTIALS_FILE_PATH} && \
      gcloud container clusters upgrade {{ cluster_name }} --master --async --cluster-version {{ version }} --location={{ zone }} --project=openenv-z7ckj --quiet 