---
- name: Close ServiceNow ticket
  hosts: localhost
  connection: local
  # using this to get the time/date
  gather_facts: true
  collections:
    - servicenow.itsm

  tasks:
    - name: Change the state of the incident {{ incident_number }} to closed
      servicenow.itsm.incident:
        state: closed
        close_code: "{{close_code}}"
        close_notes: "{{close_notes}}"
        other:
          active: false
        number: "{{ incident_number }}"