---
- name: Close ServiceNow ticket
  hosts: localhost
  connection: local
  # using this to get the time/date
  gather_facts: true
  collections:
    - servicenow.itsm

  # Use these var when running locally  
  # vars:
    # servicenow_instance: ""
    # servicenow_username: ""
    # servicenow_password: ""
    # incident_number: ""
    # close_code: "Solved (Permanently)"
    # close_notes: "Closed with ansible servicenow.itsm"

  tasks:

    - name: Change the state of the incident {{ incident_number }} to closed
      servicenow.itsm.incident:
        # Define the instance if running locally otherwise it is define by the credential.
        # instance:
        #   host: "{{ servicenow_instance }}"
        #   username: "{{ servicenow_username }}"
        #   password: "{{ servicenow_password }}"
        state: closed
        close_code: "{{close_code}}"
        close_notes: "{{close_notes}}"
        other:
          active: false
        number: "{{ incident_number }}"