---
apiVersion: v1
kind: Secret
metadata:
  name: "{{cluster_name}}-cluster-secret"
  namespace: "openshift-gitops"
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: "{{cluster_name}}"
  server: {{ gke_server.stdout }}
  config: |
   {
       "bearerToken": "{{ gke_token.stdout }}",
       "tlsClientConfig": {
       "insecure": true
     } 
   }