---
apiVersion: v1
kind: Namespace
metadata:
  name: "{{cluster_name}}"

---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: "{{cluster_name}}"
  labels:
    name: "{{cluster_name}}"
    cloud: auto-detect
    vendor: auto-detect
    cluster.open-cluster-management.io/clusterset: default
    test: "true"
  annotations: {}
spec:
  hubAcceptsClient: true

---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: "{{cluster_name}}"
  namespace: "{{cluster_name}}"
spec:
  clusterName: "{{cluster_name}}"
  clusterNamespace: "{{cluster_name}}"
  clusterLabels:
    name: "{{cluster_name}}"
    cloud: auto-detect
    vendor: auto-detect
    cluster.open-cluster-management.io/clusterset: default
    test: "true"
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true

---
apiVersion: v1
kind: Secret
metadata:
  name: auto-import-secret
  namespace: "{{cluster_name}}"
stringData:
  autoImportRetry: "2"
  token: eyJhbGciOiJSUzI1NiIsImtpZCI6InJHM3JTeUctbVQ4TE83ZXZlRTFyZXh6RUgtMDRybUc5V01qQkJCNWpwblEifQ.eyJhdWQiOlsiaHR0cHM6Ly9jb250YWluZXIuZ29vZ2xlYXBpcy5jb20vdjEvcHJvamVjdHMvb3BlbmVudi16N2Nrai9sb2NhdGlvbnMvbm9ydGhhbWVyaWNhLW5vcnRoZWFzdDEtYS9jbHVzdGVycy9teS1jbHVzdGVyIl0sImV4cCI6MTcxMjM0NjI0NywiaWF0IjoxNzEyMzQyNjQ3LCJpc3MiOiJodHRwczovL2NvbnRhaW5lci5nb29nbGVhcGlzLmNvbS92MS9wcm9qZWN0cy9vcGVuZW52LXo3Y2tqL2xvY2F0aW9ucy9ub3J0aGFtZXJpY2Etbm9ydGhlYXN0MS1hL2NsdXN0ZXJzL215LWNsdXN0ZXIiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6ImRlZmF1bHQiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiZ2dnIiwidWlkIjoiYmY0N2Y5Y2QtY2YyMy00ODZhLWI2MGMtMGI0MDAzMDk1MGFmIn19LCJuYmYiOjE3MTIzNDI2NDcsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmdnZyJ9.PrQyVm5CMpZ-uf0brUnRJkQyltwMyCtR9VPT7j1Vok4adyoPMkMzP8xVlhWXX9Di548Ue87Jb2csxP84prJmks9sipmajgEwMngoNKnoMGXfJV5eIYld1b2y_DiYrXi3MqCRP2eYqeGMR5gEPtLPxgclcahWAY9oz5Kb3sRMloOLH9YkPMDbwmUDcd4QsvzvzGpDdZdSGlLqx-e5nfyLLUXzXr_XZ7ATVvz_Vt9_En-QaCwWKjW1XCqxO6HqqH40-n39buwF1DESDRENZCYKgrEeUDpo9x802MpG9r5UFUbCmTVxD_c3Nxlw1cJylF7ByeYi_izdg3iVDJEIdxWTbg
  server: https://35.203.117.95
type: Opaque

