---
- name: Show Cluster Info
  hosts: localhost

  collections:
    - community.general
  
  tasks:

    - name: ClusterDeployment
      ansible.builtin.debug:
        msg: "{{ cluster_deployment }}"

    - name: InstallConfig
      ansible.builtin.debug:
        msg: "{{ install_config }}"

