- name: Create network
  google.cloud.gcp_compute_network:
    name: network-{{ cluster_name }}
    auto_create_subnetworks: 'true'
    project: "{{ project_id }}"
    auth_kind: serviceaccount
    service_account_file: "{{ credential }}"
    state: present
  register: network
