---
- name: Apply k8s manifests to Hub Cluster
  redhat.openshift.k8s:
    resource_definition: "{{ lookup('ansible.builtin.template', './templates/import-cluster.yaml') }}"
    state: "{{ cluster_state }}"
  register: hub_cluster_artifact

- name: debug
  ansible.builtin.debug:
    var: hub_cluster_artifact
