---
apiVersion: v1
kind: Secret
metadata:
  name: "{{cluster_name}}-cluster-secret"
  namespace: "{{cluster_name}}"
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: "{{cluster_name}}"
  server: https://{{ aks_cluster_artifact.fqdn }}
  config: |
   {
       "bearerToken": "{{ bearer_token }}",
       "tlsClientConfig": {
       "insecure": true
     } 
   }