---
apiVersion: v1
kind: Secret
metadata:
  name: "{{cluster_name}}-cluster-secret"
  namespace: "{{cluster_name}}"
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: "{{cluster_name}}"
  server: https://{{ aks_cluster_artifact.fqdn }}
  config: |
    {
      "execProviderConfig": {
        "command": "argocd-k8s-auth",
        "env": {
          "AAD_ENVIRONMENT_NAME": "AzurePublicCloud",
          "AAD_SERVICE_PRINCIPAL_CLIENT_SECRET": "{{ lookup('ansible.builtin.env', 'AZURE_SECRET') }}",
          "AZURE_TENANT_ID": "{{ lookup('ansible.builtin.env', 'AZURE_TENANT') }}",
          "AAD_SERVICE_PRINCIPAL_CLIENT_ID": "{{ lookup('ansible.builtin.env', 'AZURE_CLIENT_ID') }}",
          "AAD_LOGIN_METHOD": "spn"
        },
        "args": ["azure"],
        "apiVersion": "client.authentication.k8s.io/v1beta1"
      },
      "tlsClientConfig": {
        "insecure": false,
        "caData": ""
      }
    }

